### ISSUE TITLE
Testing compatibility between OSMDashboard and WeSki application

### ISSUE THREAD

**Issue by sha1ksadiq** [rilling/OSMDashboard-Winter-2024-SOEN-6431#33]
**Describe briefly your feature.**
Verifying the sample data between WeSki and OSMDashboard.

**Describe the solution you'd like**
Testing story performing manual testing to ensure data points and statistics are identical.

**Describe alternatives you've considered**
Perform the required physical activities and collect data in order to compare the datasets between OSMDashboard and WeSki.

**Additional context**
Verifying the compatibility ensures the correctness of the OSMDashboard application with respect to WeSki since WeSki behaves as an example as to how OSMDashboard and OpenTracks is expected to work.

**Comment by harsh9090** [comment]
Successfully validated that the newly developed features work seamlessly with the existing legacy code.
