### ISSUE TITLE
Create bar graphs for distance, duration and number of runs

### ISSUE THREAD

**Issue by KansaraDarshan** [rilling/OSMDashboard-Winter-2024-SOEN-6431#44]
**Describe briefly your feature:**
Create bar graphs for for displaying a distance graph representing distances traveled each month from January to December[ The distances are measured in kilometers] and displaying a graph for duration and number of runs.

**Describe the solution you'd like:**
- Develop a dedicated screen or section within the application interface for the distance graph.
- Implement functionality to generate the distance graph dynamically based on user data.
- Display the graph with months along the x-axis and distances (in kilometers) along the y-axis.
- Allow users to interact with the graph, such as zooming in/out, panning, or viewing specific data points.
- Ensure the graph is visually appealing and easy to understand, with clear labels and axis markers.
- Provide filter options for users to select different time periods:
- Additionally, created bar graphs for duration and number of runs to complement the distance graph, providing comprehensive insights.

![image](https://github.com/Vibhor7398/OSMDashboard-Winter-2024-SOEN-6431-Group14/assets/62127039/6e753053-50e2-42b4-953b-e55402d7e058)

**Duration Graph:**
 Display a duration graph representing time taken to travel each month from January to December. The duration is measured in hours. The graph is displayed with months along  the x-axis and duration (in hours) along the y-axis.

![image](https://github.com/Vibhor7398/OSMDashboard-Winter-2024-SOEN-6431-Group14/assets/153788658/9d17a262-711b-4e32-9c74-82e7fec1cda9)

**Number of Runs Graph**
Display a bar graph representing number of runs covered while travelling along the y-axis and month from January to December along the x-axis.

**Describe alternatives you've considered:**
- Incorporating additional features such as customizable time periods or filtering options for the graph.
- Offering different visualization types (bar graph) based on user preferences.
- Providing tooltips or legends to enhance user understanding of the graph data.

**Additional context:**
Consider optimizing the graph for responsiveness across various devices and screen sizes. Test the functionality thoroughly to ensure accurate data representation and smooth user experience. Similary create the graphs for Duration and number of runs.

**Comment by Shravanii25** [comment]
Implemented the following functionality:

1. Develop a dedicated screen or section within the application interface for the distance, duration and number of runs graph.
2. Implement functionality to generate the graphs dynamically based on random generated data.
3. Display the graph with time along the x-axis and distances (in kilometers) along the y-axis.
4. Ensure the graph is visually appealing and easy to understand, with clear labels and axis markers.

The further functionality will be implemented: #66
